routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TwitterLoginController;
use App\Http\Controllers\GoogleAuthController;
use App\Http\Controllers\EventAddController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\EventAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('top');
})->name('Home');

Route::resource('/event', 'EventController');

Route::middleware(['auth:sanctum', 'verified'])->resource('/eventauth', 'EventAuthController');

Route::post('/eventauth/change', 'EventAuthController@change')->name('event-change');

Route::middleware(['auth:sanctum', 'verified'])->get('dashboard/welcome', function () {
    return view('dashboard/welcome');
})->name('dashboard');

Route::get('auth/login/twitter', 'TwitterLoginController@redirectToProvider');
Route::get('login/twitter/callback','TwitterLoginController@handleProviderCallback');

Route::get('auth/login/google', 'GoogleAuthController@getGoogleAuth');
Route::get('login/google/callback', 'GoogleAuthController@authGoogleCallback');

Route::get('etc/policy', function () {
    return view('etc/policy');
})->name('policy');

Route::middleware(['auth:sanctum', 'verified'])->get('dashboard/event-Preview', function () {
    return view('dashboard/event-Preview');
})->name('event-Preview');

app/Http/Livewire/Avatar.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Avatar extends Component
{
    public $Avatar = "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736902/Avatars/Artboard_37.svg";

    public function push()
    {
      //0~6
      $Avatars = array(
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736902/Avatars/Artboard_37.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736902/Avatars/Artboard_38.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736902/Avatars/Artboard_36.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736901/Avatars/Artboard_35.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736901/Avatars/Artboard_34.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736901/Avatars/Artboard_33.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736900/Avatars/Artboard_31.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736900/Avatars/Artboard_32.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736900/Avatars/Artboard_30.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736899/Avatars/Artboard_29.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736899/Avatars/Artboard_28.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736898/Avatars/Artboard_27.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736898/Avatars/Artboard_26.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736896/Avatars/Artboard_22.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736898/Avatars/Artboard_25.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736897/Avatars/Artboard_24.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736897/Avatars/Artboard_23.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736896/Avatars/Artboard_21.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736895/Avatars/Artboard_19.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736894/Avatars/Artboard_16.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736895/Avatars/Artboard_20.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736895/Avatars/Artboard_18.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736895/Avatars/Artboard_17.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736894/Avatars/Artboard_15.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736893/Avatars/Artboard_14.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736893/Avatars/Artboard_10.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736893/Avatars/Artboard_11.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736893/Avatars/Artboard_12.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736893/Avatars/Artboard_13.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736892/Avatars/Artboard_1.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736891/Avatars/Artboard_42.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736891/Avatars/Artboard_44.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736891/Avatars/Artboard_43.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736891/Avatars/Artboard_39.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736891/Avatars/Artboard_41.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736891/Avatars/Artboard_40.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736793/Avatars/kidaha-07.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736793/Avatars/kidaha-05.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736793/Avatars/kidaha-06.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736793/Avatars/kidaha-03.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736793/Avatars/kidaha-02.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736793/Avatars/kidaha-04.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736791/Avatars/kidaha-01.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736791/Avatars/kidaha-08.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736791/Avatars/kidaha-09.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736791/Avatars/kidaha-10.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736791/Avatars/kidaha-11.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736791/Avatars/kidaha-12.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736621/Avatars/icons8-man-with-yellow-tie-in-jacket.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736621/Avatars/icons8-red-short-hair-lady-in-yellow-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736620/Avatars/icons8-man-with-orange-tie.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736621/Avatars/icons8-short-curly-hair-lady-in-pink-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736619/Avatars/icons8-man-with-beard-in-violet-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736618/Avatars/icons8-man-with-beard-in-suit.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736619/Avatars/icons8-man-with-brown-hair-in-green-sweater.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736616/Avatars/icons8-man-in-white-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736617/Avatars/icons8-man-in-yellow-striped-sweater.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736617/Avatars/icons8-man-in-white-shirt-2.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736616/Avatars/icons8-man-in-striped-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736615/Avatars/icons8-man-in-green-tie.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736616/Avatars/icons8-man-in-red-jacket.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736613/Avatars/icons8-indian-lady.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736614/Avatars/icons8-man-in-blue-t-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736613/Avatars/icons8-business-man-in-yellow-glasses.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736614/Avatars/icons8-man-in-green-sweater.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736614/Avatars/icons8-long-curly-hair-lady-with-glasses.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736612/Avatars/icons8-brown-short-hair-lady-in-yellow-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736612/Avatars/icons8-brown-pigtail-hair-lady.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736612/Avatars/icons8-brown-long-curly-hair-lady.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736612/Avatars/icons8-brown-long-hair-lady-with-red-glasses.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736611/Avatars/icons8-brown-hair-business-lady-with-glasses.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736612/Avatars/icons8-brown-curly-hair-lady-with-golden-earrings.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736610/Avatars/icons8-brown-curly-hair-lady-in-light-green-shirt.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736610/Avatars/icons8-two-ponytails-hair-lady-with-green-glasses.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736610/Avatars/icons8-bald-man-in-green-jacket.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736610/Avatars/icons8-blond-long-hair-business-lady.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736610/Avatars/icons8-blond-curly-hair-business-lady.svg",
        "https://res.cloudinary.com/danj8nvfr/image/upload/v1632736610/Avatars/icons8-short-hair-business-lady-with-glasses.svg"
      );
      $arr_cou = (count($Avatars) - 1 );
      $int = mt_rand(0,$arr_cou);
      $this->Avatar =$Avatars[$int];

    }

    public function render()
    {
        return view('livewire.avatar');
    }
}

app/Http/Livewire/Date.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Event;
use Carbon\Carbon;

class Date extends Component
{
    public function render()
    {
        $now = new Carbon('today','Asia/Tokyo');
        $now = $now->format('20y-m-d');

        $myevent = Event::where('date', '>', $now)->get();
        return view('livewire.date')->with('events', $myevent);
    }
}

app/Http/Livewire/Eventview.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\User;
use App\Models\Event;
use App\Models\Place;

class Eventview extends Component
{
  public function render()
  {
    $myevent = Event::where('id', 1)->first();
    $user = User::where('id',$myevent['user_id'])->first();
    $place = Place::where('id',$myevent['place_id'])->first();
    $myevent['user_name'] = $user->name;
    $myevent['user_photo'] = $user->photo;
    $myevent['place'] = $place->place;

    return view('livewire.eventview')->with('data', $myevent);
  }
}

app/Http/Livewire/makes.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\User;
use App\Models\Event;
use Illuminate\Support\Facades\Auth;

class makes extends Component
{

    public function render()
    {
        $user_id = Auth::id();
        $myevent = Event::where('user_id', $user_id)->get();
        return view('livewire.makes')->with('events', $myevent);
    }
}

resources/views/livewire/avatar.blade.php
<img wire:poll.3000ms="push" class="icon-64" src="{{ $Avatar }}" alt="Avatar">

resources/views/livewire/date.blade.php
<div>
  <table style="color:#FFF;">
    @foreach ($events as $event)
    <tr>
      <td><span>{{ $event->date }}：</span><span>{{ $event->time }}　　</span><span><a href="event/{{ $event->id }}">{{ $event->title }}</a></span></td>
    </tr>
    @endforeach
  </table>
</div>

resources/views/livewire/eventview.blade.php
<div id="top_dom" class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose xl">
  <div id="user_id" style="display:none">{{ $data['user_id'] }}</div>
  <div id="user_name" style="display:none">{{ $data['user_name'] }}</div>
  <div id="user_photo" style="display:none">{{ $data['user_photo'] }}</div>
  <div id="place" style="display:none">{{ $data['place'] }}</div>
  <div id="tag_id_1" style="display:none">{{ $data['tag_id_1'] }}</div>
  <div id="tag_id_2" style="display:none">{{ $data['tag_id_2'] }}</div>
  <div id="tag_id_3" style="display:none">{{ $data['tag_id_3'] }}</div>
  <div id="tag_id_4" style="display:none">{{ $data['tag_id_4'] }}</div>
  <div id="tag_id_5" style="display:none">{{ $data['tag_id_5'] }}</div>
  <div id="title" style="display:none">{{ $data['title'] }}</div>
  <div id="Overview" style="display:none">{{ $data['Overview'] }}</div>
  <div id="address" style="display:none">{{ $data['address'] }}</div>
  <div id="url" style="display:none">{{ $data['url'] }}</div>
  <div id="lat" style="display:none">{{ $data['lat'] }}</div>
  <div id="long" style="display:none">{{ $data['long'] }}</div>
  <div id="date" style="display:none">{{ $data['date'] }}</div>
  <div id="time" style="display:none">{{ $data['time'] }}</div>
  <div id="video" style="display:none">{{ $data['video_id'] }}</div>
  <div id="photo" style="display:none">{{ $data['photo'] }}</div>


  <h1 v-if="title !== ''" id="b_title" class="mb-3">
    @{{ title }}
  </h1>

  <div v-if="url !== ''" id="b_url" class="mb-3 flex">
    <span>URL：</span>
    <a v-bind:href="b_url">@{{ url }}</a>
  </div>

  <div v-if="Organizer !== ''" id="b_Organizer" class="mb-3 flex">
    <span>開催者：</span>
    <img class="h-8 w-8 rounded-full object-cover" src="{{ $data['user_photo'] }}" alt="{{ $data['user_name'] }}" />
    <span class="margin-left">@{{ Organizer }}</span>
  </div>

  <div class="slider">
    <div v-if="video !== ''" id="b_video" class="mb-3">
      <img id="Thumbnail" v-bind:data-video-id="video" class="js-modal-video">
      <!-- <img src="https://res.cloudinary.com/danj8nvfr/image/upload/v1633513886/play-button_igobqe.webp" alt="playbottom" class="playbottom"> -->
    </div>

    <div v-if="photo !== ''" id="b_photo"　class="mb-3">
      <img class="p_photo" v-bind:src="photo">
    </div>
  </div>

  <div v-if="place !== ''" id="b_place" class="mb-3">
    <h3>タグ</h3>
    <div class="place">@{{ place }}</div>
  </div>

  <div id="b_tag_group" class="mb-3 flex">
    <span v-if="tag1 !== ''" class="tag">@{{ tag1 }}</span>
    <span v-if="tag2 !== ''" class="tag">@{{ tag2 }}</span>
    <span v-if="tag3 !== ''" class="tag">@{{ tag3 }}</span>
    <span v-if="tag4 !== ''" class="tag">@{{ tag4 }}</span>
    <span v-if="tag5 !== ''" class="tag">@{{ tag5 }}</span>
  </div>

  <div v-if="oview !== ''" id="b_Overview" class="mb-3">
    <h3>イベント詳細</h3>
    <div>@{{ oview }}</div>
  </div>

  <div id="b_data_time" class="mb-3">
    <h3>開催日時</h3>
    <span id="data">@{{ date }}</span>
    <span id="time">@{{ time }}</span>
  </div>

  <div v-if="address !== ''" id="b_address" class="mb-3">
    <h3>開催場所</h3>
    <div>@{{ address }}</div>
  </div>

  <div class="content">
    <div class="box">
      <div id="map"></div>
    </div>
  </div>

</div>

resources/views/livewire/makes.blade.php
<div>
  <table class="table table-striped">
    @foreach ($events as $event)
    <tr>
      <td><a href="{{route('eventauth.edit', $event)}}">{{ $event->title }}</a></td>
    </tr>
    @endforeach
  </table>
</div>