routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TwitterLoginController;
use App\Http\Controllers\GoogleAuthController;
use App\Http\Controllers\EventAddController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\EventAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('top');
})->name('Home');

Route::resource('/event', 'EventController');

Route::middleware(['auth:sanctum', 'verified'])->resource('/eventauth', 'EventAuthController');

Route::post('/eventauth/change', 'EventAuthController@change')->name('event-change');

Route::middleware(['auth:sanctum', 'verified'])->get('dashboard/welcome', function () {
    return view('dashboard/welcome');
})->name('dashboard');

Route::get('auth/login/twitter', 'TwitterLoginController@redirectToProvider');
Route::get('login/twitter/callback','TwitterLoginController@handleProviderCallback');

Route::get('auth/login/google', 'GoogleAuthController@getGoogleAuth');
Route::get('login/google/callback', 'GoogleAuthController@authGoogleCallback');

Route::get('etc/policy', function () {
    return view('etc/policy');
})->name('policy');

Route::middleware(['auth:sanctum', 'verified'])->get('dashboard/event-Preview', function () {
    return view('dashboard/event-Preview');
})->name('event-Preview');

app/Http/Controllers/EventAuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Event;
use App\Models\Place;
use Illuminate\Support\Facades\Auth;
use JD\Cloudder\Facades\Cloudder;

class EventAuthController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('eventauth.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->session()->regenerateToken();

    $event = new Event;
    $user_id = Auth::id();
    $user_name = User::find($user_id)->name;
    $user_photo = User::find($user_id)->photo;
    $place = Place::find($request['place_id_Radios'])->place;
    // イベントDBに反映
    if (!$event->exists) {
      if($request['eventVideo'] != ''){
        preg_match("/^(?:http(?:s)?:\/\/)?(?:www\.)?(?:m\.)?(?:youtu\.be\/|youtube\.com\/(?:(?:watch)?\?(?:.*&)?v(?:i)?=|(?:embed|v|vi|user)\/))([^\?&\"'>]+)/",$request['eventVideo'], $matches);
        $matches = $matches[1];
        $event['video'] = $request['eventVideo'];
        $event['video_id'] = $matches;
      }
      if($request['id'] != null){
        $event['id'] = $request['id'];
      }
      $event['user_id'] = $user_id;
      $event['place_id'] = $request['place_id_Radios'];
      $event['tag_id_1'] = $request['tag1'];
      $event['tag_id_2'] = $request['tag2'];
      $event['tag_id_3'] = $request['tag3'];
      $event['tag_id_4'] = $request['tag4'];
      $event['tag_id_5'] = $request['tag5'];
      $event['title'] = $request['title'];
      $event['Overview'] = $request['event-Overview'];
      $event['address'] = $request['address'];
      $event['url'] = $request['eventUrl'];
      $event['lat'] = $request['lat'];
      $event['long'] = $request['long'];
      $event['date'] = $request['date'];
      $event['time'] = $request['time'];
      if ($image = $request->file('image')) {
        $size = $this->get_image_size($request->file('image'));
        $image_path = $image->getRealPath();
        Cloudder::upload($image_path, null);
        $publicId = Cloudder::getPublicId();
        $logoUrl = Cloudder::secureShow($publicId, [
          'width'     => $size[0],
          'height'    => $size[1]
        ]);
        $event['photo'] = $logoUrl;
        $event['public_id']  = $publicId;
      }

      $event->save();
      $event['user_name'] = $user_name;
      $event['user_photo'] = $user_photo;
      $event['place'] = $place;
      return view('eventauth/show')->with('data', $event);
    }else{
      return redirect()->route('dashboard');
    }
}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    { 
 
        $event = Event::find($id);
        $user_id = $event['user_id'];
        $user_name = User::find($user_id)->name;
        $user_photo = User::find($user_id)->photo;

        $place = Place::find($event['place_id'])->place;
        $event['user_name'] = $user_name;
        $event['user_photo'] = $user_photo;
        $event['place'] = $place;
        $event['place'] = $place;
        return view('eventauth.edit')->with('data', $event);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function change(Request $request)
    {
        $request->session()->regenerateToken();

    $event = Event::find($request['id']);
    $place = Place::find($request['place_id_Radios'])->place;
    // イベントDBに反映

    if($request['eventVideo'] != ''){
      preg_match("/^(?:http(?:s)?:\/\/)?(?:www\.)?(?:m\.)?(?:youtu\.be\/|youtube\.com\/(?:(?:watch)?\?(?:.*&)?v(?:i)?=|(?:embed|v|vi|user)\/))([^\?&\"'>]+)/",$request['eventVideo'], $matches);
      $matches = $matches[1];
      $event['video'] = $request['eventVideo'];
      $event['video_id'] = $matches;
    }
    $event['place_id'] = $request['place_id_Radios'];
    $event['tag_id_1'] = $request['tag1'];
    $event['tag_id_2'] = $request['tag2'];
    $event['tag_id_3'] = $request['tag3'];
    $event['tag_id_4'] = $request['tag4'];
    $event['tag_id_5'] = $request['tag5'];
    $event['title'] = $request['title'];
    $event['Overview'] = $request['event-Overview'];
    $event['address'] = $request['address'];
    $event['url'] = $request['eventUrl'];
    $event['lat'] = $request['lat'];
    $event['long'] = $request['long'];
    $event['date'] = $request['date'];
    $event['time'] = $request['time'];
    $size = $this->get_image_size($request->file('image'));
    if ($image = $request->file('image')) {
      $this->destroy($request['id']);
      $image_path = $image->getRealPath();
      Cloudder::upload($image_path, null);
      $publicId = Cloudder::getPublicId();
      $logoUrl = Cloudder::secureShow($publicId, [
        'width'     => $size[0],
        'height'    => $size[1]
      ]);
      $event['photo'] = $logoUrl;
      $event['public_id']  = $publicId;
    }

    $event->save();
    $event['place'] = $place;
    return view('eventauth/show')->with('data', $event);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = event::find($id);
    
        if(Auth::id() !== $event['user_id']){
          return abort(404);
        }
    
        if(isset($event['public_id'])){
          Cloudder::destroyImage($event['public_id']);
    }
    }

    public function get_image_size($file){
        $size = [0, 0];
        if(file_exists($file)){
          $size = getimagesize($file);
          if($size){
            $size = [$size[0], $size[1]];
          }
        }
        return $size;
      }
    
}

resources/views/eventauth/change.blade.php
@include('cdn.bootstrap')
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
@extends('layouts.guest')
@section('content')
  <div class="pt-4 bg-gray-100">
    <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
      <div>
        <img class="icon-128" src="https://res.cloudinary.com/danj8nvfr/image/upload/v1632648264/announcement_c7srjz.svg" alt="crete">
      </div>
      <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose xl">
        <div id="user_id" style="display:none">{{ $data['user_id'] }}</div>
        <div id="user_name" style="display:none">{{ $data['user_name'] }}</div>
        <div id="user_photo" style="display:none">{{ $data['user_photo'] }}</div>
        <div id="place" style="display:none">{{ $data['place'] }}</div>
        <div id="tag_id_1" style="display:none">{{ $data['tag_id_1'] }}</div>
        <div id="tag_id_2" style="display:none">{{ $data['tag_id_2'] }}</div>
        <div id="tag_id_3" style="display:none">{{ $data['tag_id_3'] }}</div>
        <div id="tag_id_4" style="display:none">{{ $data['tag_id_4'] }}</div>
        <div id="tag_id_5" style="display:none">{{ $data['tag_id_5'] }}</div>
        <div id="title" style="display:none">{{ $data['title'] }}</div>
        <div id="Overview" style="display:none">{{ $data['Overview'] }}</div>
        <div id="address" style="display:none">{{ $data['address'] }}</div>
        <div id="url" style="display:none">{{ $data['url'] }}</div>
        <div id="lat" style="display:none">{{ $data['lat'] }}</div>
        <div id="long" style="display:none">{{ $data['long'] }}</div>
        <div id="date" style="display:none">{{ $data['date'] }}</div>
        <div id="time" style="display:none">{{ $data['time'] }}</div>
        <div id="video" style="display:none">{{ $data['video_id'] }}</div>
        <div id="photo" style="display:none">{{ $data['photo'] }}</div>


        <h1 v-if="title !== ''" id="b_title" class="mb-3">
          @{{ title }}
        </h1>

        <div v-if="url !== ''" id="b_url" class="mb-3 flex">
          <span>URL：</span>
          <a v-bind:href="b_url">@{{ url }}</a>
        </div>

        <div v-if="Organizer !== ''" id="b_Organizer" class="mb-3 flex">
          <span>開催者：</span>
          <img class="h-8 w-8 rounded-full object-cover" src="{{ $data['user_photo'] }}" alt="{{ $data['user_name'] }}" />
          <span class="margin-left">@{{ Organizer }}</span>
        </div>

        <div class="slider">
          <div v-if="video !== ''" id="b_video" class="mb-3">
            <img id="Thumbnail" v-bind:data-video-id="video" class="js-modal-video">
            <!-- <img src="https://res.cloudinary.com/danj8nvfr/image/upload/v1633513886/play-button_igobqe.webp" alt="playbottom" class="playbottom"> -->
          </div>

          <div v-if="photo !== ''" id="b_photo"　class="mb-3">
            <img class="p_photo" v-bind:src="photo">
          </div>
        </div>

        <div v-if="place !== ''" id="b_place" class="mb-3">
          <h3>タグ</h3>
          <div class="place">@{{ place }}</div>
        </div>

        <div id="b_tag_group" class="mb-3 flex">
          <span v-if="tag1 !== ''" class="tag">@{{ tag1 }}</span>
          <span v-if="tag2 !== ''" class="tag">@{{ tag2 }}</span>
          <span v-if="tag3 !== ''" class="tag">@{{ tag3 }}</span>
          <span v-if="tag4 !== ''" class="tag">@{{ tag4 }}</span>
          <span v-if="tag5 !== ''" class="tag">@{{ tag5 }}</span>
        </div>

        <div v-if="oview !== ''" id="b_Overview" class="mb-3">
          <h3>イベント詳細</h3>
          <div>@{{ oview }}</div>
        </div>

        <div id="b_data_time" class="mb-3">
          <h3>開催日時</h3>
          <span id="data">@{{ date }}</span>
          <span id="time">@{{ time }}</span>
        </div>

        <div v-if="address !== ''" id="b_address" class="mb-3">
          <h3>開催場所</h3>
          <div>@{{ address }}</div>
        </div>

        <div class="content">
          <div class="box">
            <div id="map"></div>
          </div>
        </div>



      </div>
    </div>
  </div>

  <script src="{{ mix('js/eventadd.js') }}" defer></script>
  @include('parts.google-map')
  @include('javascript.modal-video')
  @include('cdn.stick')
@endsection

resources/views/eventauth/create.blade.php
@include('cdn.bootstrap')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
@extends('layouts.guest')
@section('content')
  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        イベント作成
      </h2>
    </div>
  </header>
  <div class="py-12">
    <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
      <div>
        <img src="https://res.cloudinary.com/danj8nvfr/image/upload/v1632124766/icons8-%E3%83%A1%E3%82%AC%E3%83%9B%E3%83%B3-96_pletbm.webp" alt="megaphon">
      </div>

      <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose xl">

        <h1 class="fs-1">イベント作成</h1>
        <form action="{{ route('eventauth.store')}}" method="POST" enctype="multipart/form-data">
          @csrf
          <!-- イベント形式 -->
          <h2>イベント形態</h2>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="place_id_Radios" id="place_id_Radios_1" value="1" checked>
            <label class="form-check-label" for="place_id_Radios_1">
              オンライン
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="place_id_Radios" id="place_id_Radios_2" value="2">
            <label class="form-check-label" for="place_id_Radios_2">
              オフライン
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="place_id_Radios" id="place_id_Radios_3" value="3">
            <label class="form-check-label" for="place_id_Radios_3">
              両方
            </label>
          </div>
          <!-- イベント形式 -->
          <!-- タイトル -->
          <h3>イベント名</h3>
          <div class="mb-3">
            <input type="title" class="form-control" id="title" name="title" required>
          </div>
          <!-- タイトル -->
          <!-- 概要 -->
          <h3>イベント詳細</h3>
          <div class="mb-3">
            <textarea class="form-control" id="event-Overview" name="event-Overview" placeholder="空欄でも大丈夫です"></textarea>
          </div>
          <!-- 概要 -->
          <!-- タグ -->
          <h3>タグを付ける</h3>
          <div class="mb-3" id="tags"><button type="button" class="btn btn-primary" id="tag-add">タグを増やす</button>
            <input type="tag" class="form-control" id="tag" name="tag1" placeholder="最大5個までつけれます">
          </div>
          <!-- タグ -->
          <!-- 場所 -->
          <div class="online" style="display:none">
            <h3>イベント開催地</h3>
            <div class="mb-3">
              <textarea class="form-control" id="address" name="address"></textarea>
              <button type="button" class="btn btn-primary" id="address-fix" name="address-fix">地図で表示</button>
            </div>
          </div>
          <!-- 場所 -->
          <div class="online" style="display:none">
            <div class="content" style="display:none">
              <div class="box">
                <div id="map"></div>
              </div>
            </div>
          </div>
          <div class="mb-3">
            <!-- 緯度経度 -->
            <input type="lat" class="form-control" id="lat" name="lat" style="display:none">
            <input type="long" class="form-control" id="long" name="long" style="display:none">
          </div>
          <!-- 場所 -->
          <!-- イベントUR? -->
          <h3>イベントURL</h3>
          <div class="mb-3">
            <input type="title" class="form-control" id="event-url" name="eventUrl" pattern="https?://[\w!?/+\-_~;.,*&@#$%()'[\]]+" placeholder="https or http">
          </div>
          <!-- イベントURL -->
          <!-- 開催日-->
          <!-- 開始時間 -->
          <h3>開催日：開始時間</h3>
          <div class="mb-3">
            <input id="datepickerfrom" type="date" name="date" required />
            <input id="datepickerfrom" type="time" name="time" required />
          </div>
          <!-- 開催予定日 -->
          <!-- 開始時間 -->
          <!-- イベント告知写真 -->
          <h3>イベント告知写真</h3>
          <div class="photo-content">
            <div class="box">
              <div x-data="{photoName: null, photoPreview: null}" class="col-span-6 sm:col-span-4">
                <input type="file" class="hidden" id="edit_image" name="image"
                wire:model="photo"
                x-ref="photo"
                x-on:change="
                photoName = $refs.photo.files[0].name;
                const reader = new FileReader();
                reader.onload = (e) => {
                  photoPreview = e.target.result;
                };
                reader.readAsDataURL($refs.photo.files[0]);
                " />
                <div class="mt-2" x-show="photoPreview">
                  <span class="block event-photo bg-no-repeat bg-center" id="Preview"
                  x-bind:style="'background-image: url(\'' + photoPreview + '\');'">
                </span>
              </div>

              <x-jet-secondary-button class="mt-2 mr-2" type="button" x-on:click.prevent="$refs.photo.click()">
                {{ __('写真を貼る') }}
              </x-jet-secondary-button>
              <button type="button" class="btn btn-primary" id="Preview-fix" style="display:none">比率を合わせる</button>
            </div>
          </div>
        </div>
        <!-- イベント告知写真 -->
        <!-- イベント告知動画 -->
        <h3>イベント告知動画(今のところyoutubeだけです)</h3>
        <div class="mb-3">
          <input type="title" class="form-control" id="event-video" name="eventVideo" pattern="https\:\/\/)?(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/)+[\S]{11}\" placeholder="https or http">
        </div>
        <!-- イベント告知動画 -->
        <div class="mb-3">
          <button type="submit" class="btn btn-primary btn-lg btn-block" value="submit">イベント作成</button>
        </div>
      </form>
    </div>
  </div>
</div>
<script src="{{ mix('js/event-crate.js') }}" async></script>
@include('parts.google-map')
@endsection

resources/views/eventauth/edit.blade.php
@include('cdn.bootstrap')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
@extends('layouts.guest')
@section('content')
  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        イベント編集
      </h2>
    </div>
  </header>
  <div class="py-12">
    <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
      <div>
        <img class="icon-128" src="https://res.cloudinary.com/danj8nvfr/image/upload/v1632648264/announcement_c7srjz.svg" alt="edit">
      </div>

      <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose xl">

        <h1 class="fs-1">イベント作成</h1>
        <form action="{{ route('event-change')}}" method="POST" enctype="multipart/form-data">
          @csrf
          <!-- イベント形式 -->
          <h2>イベント形態</h2>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="place_id_Radios" id="place_id_Radios_1" value="1">
            <label class="form-check-label" for="place_id_Radios_1">
              オンライン
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="place_id_Radios" id="place_id_Radios_2" value="2">
            <label class="form-check-label" for="place_id_Radios_2">
              オフライン
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="place_id_Radios" id="place_id_Radios_3" value="3">
            <label class="form-check-label" for="place_id_Radios_3">
              両方
            </label>
          </div>
          <!-- イベント形式 -->
          <!-- タイトル -->
          <h3>イベント名</h3>
          <div class="mb-3">
            <input type="title" class="form-control" id="title" name="title" required value="{{ $data['title']}}">
          </div>
          <!-- タイトル -->
          <!-- 概要 -->
          <h3>イベント詳細</h3>
          <div class="mb-3">
            <textarea class="form-control" id="event-Overview" name="event-Overview">{{ $data['Overview']}}</textarea>
          </div>
          <!-- 概要 -->
          <!-- タグ -->
          <h3>タグを付ける</h3>
          <div class="mb-3" id="tags">
            <input type="tag" class="form-control" id="tag" name="tag1" value="{{ $data['tag_id_1']}}">
            <input type="tag" class="form-control" id="tag" name="tag2" value="{{ $data['tag_id_2']}}">
            <input type="tag" class="form-control" id="tag" name="tag3" value="{{ $data['tag_id_3']}}">
            <input type="tag" class="form-control" id="tag" name="tag4" value="{{ $data['tag_id_4']}}">
            <input type="tag" class="form-control" id="tag" name="tag5" value="{{ $data['tag_id_5']}}">
          </div>
          <!-- タグ -->
          <!-- 場所 -->
          <div class="online" style="display:none">
            <h3>イベント開催地</h3>
            <div class="mb-3">
              <textarea class="form-control" id="address" name="address">{{ $data['address']}}</textarea>
              <button type="button" class="btn btn-primary" id="address-fix" name="address-fix">地図で表示</button>
            </div>
          </div>
          <!-- 場所 -->
          <div class="online" style="display:none">
            <div class="content" style="display:none">
              <div class="box">
                <div id="map"></div>
              </div>
            </div>
          </div>
          <div class="mb-3">
            <!-- 緯度経度 -->
            <input type="lat" class="form-control" id="lat" name="lat" style="display:none" value="{{ $data['lat']}}">
            <input type="long" class="form-control" id="long" name="long" style="display:none" value="{{ $data['long']}}">
          </div>
          <!-- 場所 -->
          <!-- イベントUR? -->
          <h3>イベントURL</h3>
          <div class="mb-3">
            <input type="title" class="form-control" id="event-url" name="eventUrl" pattern="https?://[\w!?/+\-_~;.,*&@#$%()'[\]]+" value="{{ $data['url']}}">
          </div>
          <!-- イベントURL -->
          <!-- 開催日-->
          <!-- 開始時間 -->
          <h3>開催日：開始時間</h3>
          <div class="mb-3">
            <input id="datepickerfrom" type="date" name="date" required value="{{ $data['date']}}"/>
            <input id="datepickerfrom" type="time" name="time" required value="{{ $data['time']}}"/>
          </div>
          <!-- 開催予定日 -->
          <!-- 開始時間 -->
          <!-- イベント告知写真 -->
          <h3>イベント告知写真</h3>
          <div class="photo-content">
            <div class="box">
              <div x-data="{photoName: null, photoPreview: null}" class="col-span-6 sm:col-span-4">
                <input type="file" class="hidden" id="edit_image" name="image"
                wire:model="photo"
                x-ref="photo"
                x-on:change="
                photoName = $refs.photo.files[0].name;
                const reader = new FileReader();
                reader.onload = (e) => {
                  photoPreview = e.target.result;
                };
                reader.readAsDataURL($refs.photo.files[0]);
                " />
                <div class="mt-2" x-show="photoPreview" id="div_Preview">
                  <span class="block event-photo bg-no-repeat bg-center" id="Preview"
                  x-bind:style="'background-image: url(\'' + photoPreview + '\');'">
                </span>
              </div>

              <x-jet-secondary-button class="mt-2 mr-2" type="button" x-on:click.prevent="$refs.photo.click()">
                {{ __('写真を貼る') }}
              </x-jet-secondary-button>
              <button type="button" class="btn btn-primary" id="Preview-fix" style="display:none">比率を合わせる</button>
            </div>
          </div>
        </div>
        <!-- イベント告知写真 -->
        <!-- イベント告知動画 -->
        <h3>イベント告知動画(今のところyoutubeだけです)</h3>
        <div class="mb-3">
          <input type="title" class="form-control" id="event-video" name="eventVideo" pattern="https\:\/\/)?(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/)+[\S]{11}\" value="{{ $data['video']}}">
        </div>
        <!-- イベント告知動画 -->
        <div class="mb-3">
          <button type="submit" class="btn btn-primary btn-lg btn-block" value="submit">イベント作成</button>
        </div>
        <!-- 更新か確認する -->
        <input type="page" name="id" value="{{ $data['id']}}" style="display:none"/>
        <div style="display:none" ID="place_id">{{ $data['place_id']}}</div>
        <div style="display:none" ID="load_lat">{{ $data['lat']}}</div>
        <div style="display:none" ID="load_long">{{ $data['long']}}</div>
        <div style="display:none" ID="load_photo">{{ $data['photo']}}</div>
      </form>
    </div>
  </div>
</div>
<script src="{{ mix('js/event-crate.js') }}" async></script>
@include('parts.google-map')
@endsection